### ISSUE TITLE
Remove tower from Base agent struct

### ISSUE THREAD

**Issue by jzzheng22** [SOMAS2021/SOMAS2021#19]
I think it's cleaner if instead of containing tower inside the struct of base agent, we just pass a reference to tower inside the `Run()` function.

Agents shouldn't contain the tower inside their structs in my opinion

**Comment by JaafarRammal** [comment]
If the tower does not contain any tower-state alternating functions or agent-state alternating functions then yes, otherwise it is not safe to expose the tower directly to any custom agents (not because we don't trust agent teams, but because it means extra testing and review has to be done to ensure no unexpected behavior happens given that the tower is now accessible). We get definite control over those state alternations if the tower is passed to an intermediate base agent instead

**Comment by jzzheng22** [comment]
Probably not worth the effort at this point.
