### ISSUE TITLE
[APP] Handle timeout

### ISSUE THREAD

**Issue by JaafarRammal** [SOMAS2021/SOMAS2021#212]
Currently incomplete logs look fine even if they timeout. Either delete them and tell frontend, or add something in the name so frontend tells user the log had timeout
- [x] Backend support to signal log status in some way
- [ ] Frontend to reflect this to user

**Comment by VFjr** [comment]
I am proposing to edit the folder name of the log. For example, I could add "- timed out" at the end, so then it will be easy to see that in the frontend. And also, I guess timed out simulations might still be useful since I guess we should be able to open them and see how they progressed until the cut off, so I think this would be a better solution than just deleting all of them. What do you think?

**Comment by JaafarRammal** [comment]
Yes!
I think it's even easier to handle on the frontend if we have a single file "status.json" with a single line saying the status of the run? then if it's currently running we can see it evolving in real time (we already have this at the frontend but currently just force-refreshing it instead of checking sim status)
