### ISSUE TITLE
Limit how much food an agent can take in a single call to `Run()`

### ISSUE THREAD

**Issue by jzzheng22** [SOMAS2021/SOMAS2021#44]
This will allow agents to take food in each `Tick`. Currently agents can take food only once per day.

- [x] This issue requires #13  to be closed first
- [ ] Decide how much food an agent can realistically take in a single tick
- [ ] Remove `setHasEaten()` and `hasEaten`

**Comment by Rhys-J** [comment]
I think limiting food to per Run, not per day makes it more complicated for agent teams to implement strategies. As if they decided on a food amount per day they would have to internally check if they'd already eaten (like is done forcefully now), or know how many ticks they have to take food and do so accordingly if taking across multiple ticks

**Comment by Rhys-J** [comment]
I think I've had a change of opinion about this but its dependent on how we view floors in the tower.
If multiple agents are on the same floor, are we viewing them as equal (or as equal as possible) in their ability to take food? If yes, then I think the most equal way to do this (in the MVP implementation at least) is to limit food take to 1 per tick. 
This would then link with issue #13, because I think the platform should then stay on each floor for as many ticks equal to the starting food on the platform. This would allow for any individual agent to always have the opportunity to take all the food from the platform if they so wished to.

**Comment by jzzheng22** [comment]
Does taking all the food from the tower include destroying the food on the tower? If so then yes, but otherwise we should limit how much food an agent can take per tick/per movement of the platform - there is a physical limit to how much someone can eat in a given period of time.

**Comment by AdrianKoch3010** [comment]
FYI: There is also a relevant discussion in the health decay channel on slack

**Comment by jzzheng22** [comment]
Closed by #262
