### ISSUE TITLE
Add unique IDs to messages

### ISSUE THREAD

**Issue by JaafarRammal** [SOMAS2021/SOMAS2021#56]
We can have a unique ID attached to each message so agents can register states easily (for example remember which messages have been acknowledged, which messages have been ghosted). Then this can be used to answer messages.

For example:
- A sends to B message M1
- A sends to C message M2
- D sends to C message M3

A and C can now remember in their states that they have two messages pending. If someone replied ACK to A, they can also append the message ID, so A knows which message has been acknowledged

**Comment by MattScottEEE** [comment]
Is an acknowledgment message totally necessary? Surely, for realism, agents would have to respond within the same day (as otherwise dialogue wouldn't exist). Agents can hence work out if a message was acknowledged by converse argument - if they get a response then it's fine, else they've been ghosted

**Comment by JaafarRammal** [comment]
That's a good point

Although note this is note about ACK message but about messages in general. It will help agents sort messages into conversations.

TBF, appending a conversation ID makes more sense and makes it even easier to manage. Will think about that when implementing
